version: '3'
services:
  db:
    image: mysql:latest  # 使用MySQL镜像作为初始化服务的基础镜像
    env_file:
      - .env # 通过.env配置密码
    environment:
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    # 将本地主机上的./init-scripts目录挂载到MySQL容器内的/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  outerview-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    image: outerview-backend-image:latest
     # 确保db-init服务启动后再启动outerview_backend服务
    depends_on:
      - db
